export const event = {
  resource: '/',
  path: '/shops',
  httpMethod: 'GET',
  headers: {
    Accept: '*/*',
    'Cloudfront-Forwarded-Proto': 'https',
    'Cloudfront-Is-Desktop-Viewer': 'true',
    'Cloudfront-Is-Mobile-Viewer': 'false',
    'Cloudfront-Is-Smarttv-Viewer': 'false',
    'Cloudfront-Is-Tablet-Viewer': 'false',
    'Cloudfront-Viewer-Country': 'DK',
    Host: 'api-dev.simplepipeline.xyz',
    'User-Agent': 'curl/7.54.0',
    Via: '2.0 e49f22f18c16784c0f42291e768d1daa.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'jvXLvEGHXCZfY5Va8hvpuHaM5IGKVBXLNS5O1WQnENQ5gOfvaxfE2w==',
    'X-Amzn-Trace-Id': 'Root=1-5b6dede1-79a3d761bf7ceff287d09d39',
    'X-Forwarded-For': '213.32.242.95, 70.132.12.92',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
  },
  queryStringParameters: {
    id: '1',
  },
  pathParameters: {},
  stageVariables: null,
  requestContext: {
    resourceId: 'tbqoklr9ug',
    resourcePath: '/',
    httpMethod: 'GET',
    extendedRequestId: 'LbIbNGU8joEFXXw=',
    requestTime: '10/Aug/2018:19:56:17 +0000',
    path: '/shops',
    accountId: '275307759108',
    protocol: 'HTTP/1.1',
    stage: 'dev',
    requestTimeEpoch: 1533930977349,
    requestId: '71a747ff-9cd7-11e8-82c6-df1b2a18effe',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '213.32.242.95',
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'curl/7.54.0',
      user: null,
    },
    apiId: '9dxnp2wbxb',
  },
  body: null,
  isBase64Encoded: false,
  rawHeaders: {
    Accept: '*/*',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'DK',
    Host: 'api-dev.simplepipeline.xyz',
    'User-Agent': 'curl/7.54.0',
    Via: '2.0 e49f22f18c16784c0f42291e768d1daa.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'jvXLvEGHXCZfY5Va8hvpuHaM5IGKVBXLNS5O1WQnENQ5gOfvaxfE2w==',
    'X-Amzn-Trace-Id': 'Root=1-5b6dede1-79a3d761bf7ceff287d09d39',
    'X-Forwarded-For': '213.32.242.95, 70.132.12.92',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
  },
}
