const event = {
  resource: '/shops',
  path: '/shops',
  httpMethod: 'GET',
  headers: {
    Accept: '*/*',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'DK',
    Host: 'edcpmry6c1.execute-api.eu-west-1.amazonaws.com',
    'User-Agent': 'curl/7.54.0',
    Via: '2.0 bc9bd2c59aa48e2932432099ba36a25b.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'V_nhaf-PtHHKjCRvhfSqkaHPPGzJ690wDBUkNF_BkGSGrHiSikZ87A==',
    'X-Amzn-Trace-Id': 'Root=1-5b380ca4-40d94aa0959d8e607415d648',
    'X-Forwarded-For': '213.32.242.74, 54.182.243.102',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
  },
  queryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'bcn5v5',
    resourcePath: '/shops',
    httpMethod: 'GET',
    extendedRequestId: 'JUbpoHepDoEFzOg=',
    requestTime: '30/Jun/2018:23:05:08 +0000',
    path: '/dev/shops',
    accountId: '275307759108',
    protocol: 'HTTP/1.1',
    stage: 'dev',
    requestTimeEpoch: 1530399908076,
    requestId: '085b43a9-7cba-11e8-b375-6be0c57f08f5',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '213.32.242.74',
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'curl/7.54.0',
      user: null,
    },
    apiId: 'edcpmry6c1',
  },
  body: null,
  isBase64Encoded: false,
}

export { event }
